service: clinicians-api

package:
  individually: true

plugins:
  - serverless-bundle # Package lambdas with Webpack
  - serverless-add-api-key # allow re-using of apiKeys across services

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage,'dev'}
  region: us-west-2
  lambdaHashingVersion: 20201221
  apiGateway:
    apiKeys:
      - eapProviders:
        - ${opt:stage}-thirdPartyApiKey
    usagePlan:
      - eapProviders:
          quota:
            limit: 10000
            offset: 2
            period: MONTH
          throttle:
            burstLimit: 2000
            rateLimit: 1000


functions:
  list:
    handler: list.handler
    environment:
      MONARCH_BASE_URL: ${ssm:/${opt:stage,'dev'}-api-url}
      MONARCH_BASIC_AUTH: ${ssm:/${opt:stage,'dev'}-basic-auth}
    events:
      - http:
          path: clinicians
          method: get
          integration: lambda
          private: true
          response:
            template: ${file(templates/clinicians-output)}
